[package]
name = "slingshot"
version = "0.1.0"
edition = "2021"
description = "Async runtime that work with std types"
repository = "https://github.com/ultimicro/slingshot"
license = "MIT"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
