name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  linux:
    name: Build (Linux)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Check code styles
      run: cargo fmt --check
    - name: Run Clippy
      run: cargo clippy -- -D warnings
  mac:
    name: Build (macOS)
    runs-on: macos-12
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Run Clippy
      run: cargo clippy -- -D warnings
  windows:
    name: Build (Windows)
    runs-on: windows-2022
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Run Clippy
      run: cargo clippy -- -D warnings
